name = "link"
main = "src/index.ts"
compatibility_date = "2022-05-30"

[[kv_namespaces]]
binding = "REDIRECTS"
id = "L_ENV.WORKER_ID"
preview_id = "L_ENV.WORKER_PREVIEW_ID"

[vars]
GITHUB_CLIENT_ID = "L_ENV.GITHUB_CLIENT_ID"
GITHUB_CLIENT_SECRET = "L_ENV.GITHUB_CLIENT_SECRET"
